= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.11.3...v0.11.4++[0.11.4^] (2021-01-14)

=== Bug Fixes

* *_mapdata:* ensure map data is directly under `values`
(https://github.com/saltstack-formulas/dhcpd-formula/commit/81fb96012d75e2e19784451e90fa5dd0e5e9ad17[81fb960^])

=== Tests

* *_mapdata:* update for `_mapdata/init.sls` change
(https://github.com/saltstack-formulas/dhcpd-formula/commit/743de98b2f38201e396552346eb139bf46407e8b[743de98^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.11.2...v0.11.3++[0.11.3^] (2020-12-27)

=== Continuous Integration

* *commitlint:* ensure `upstream/master` uses main repo URL [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/8c22f0bea349fdfb5ab786b48c025d700f6e9ff8[8c22f0b^])
* *gitlab-ci:* add `rubocop` linter (with `allow_failure`) [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/b7dcffabfc4f9393999f934d91cab94037c4c236[b7dcffa^])
* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/dhcpd-formula/commit/487fd0b901f82e955fbb0554013420ad40713189[487fd0b^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/7814d97b658d8fbb8096778f5c23a34681a120fd[7814d97^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/1a76032e5078e5211ea8ee7f5563b4af9735861f[1a76032^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/52c33c9047033ec0ccb9ccf01996b9a37c871e33[52c33c9^])

=== Tests

* *_mapdata:* generate verification files
(https://github.com/saltstack-formulas/dhcpd-formula/commit/2ffc825c1d2b267b81a876de3886d0ffb4e7a011[2ffc825^])
* *map:* verify `map.jinja` dump using `_mapdata` state
(https://github.com/saltstack-formulas/dhcpd-formula/commit/c8fbc79ec2443ec45881ce81f0500702e8d27400[c8fbc79^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.11.1...v0.11.2++[0.11.2^] (2020-09-24)

=== Bug Fixes

* *dhcpd.conf:* fix bug 50
(https://github.com/saltstack-formulas/dhcpd-formula/commit/e015cdac5944cba0d821da31108ca26fe43a2da5[e015cda^]),
closes
https://github.com/saltstack-formulas/dhcpd-formula/issues/50[#50^]

=== Continuous Integration

* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/e3d3bb3b93f5686f3a32d411106de39d5b71fe9e[e3d3bb3^])
* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/6e5d4fe5ff331fea4fe6b63bbfe0db71d01523f5[6e5d4fe^])
* *kitchen+travis:* add new platforms [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/2e3f86ee12a0c1bab6c598f21109eaadc4ef790e[2e3f86e^])
* *kitchen+travis:* adjust matrix to add `3000.2` & remove `2018.3`
 [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/1eac3c9c4d8a352f0a8c2d9b68faeafae47acc71[1eac3c9^])
* *kitchen+travis:* adjust matrix to add `3000.3` [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/4fa9cb54eeb4de109da50bf24766dca81a6cce23[4fa9cb5^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/aa2f8818fab95889e1365f331bb71468c212bf45[aa2f881^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/1726c5a2c4a0ca2beb52b57795f6aa9cd8f3ca25[1726c5a^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/9572bd82e3659354eca0d6061f1af566a2cbad23[9572bd8^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.11.0...v0.11.1++[0.11.1^] (2020-04-09)

=== Bug Fixes

* *fedora:* install `dhcp-server`
(https://github.com/saltstack-formulas/dhcpd-formula/commit/b91a3b1feb1d5e524eed26c6e5be014f1bd33435[b91a3b1^])
* *pillar.example:* remove spurious whitespaces found in `yaml_dump`
(https://github.com/saltstack-formulas/dhcpd-formula/commit/d57899643ea6be24b364bb5361034c120ee07ecd[d578996^])
* *rubocop:* fix remaining violations
(https://github.com/saltstack-formulas/dhcpd-formula/commit/106f9cb36d8710b48c327541616347c7f94bea76[106f9cb^])

=== Continuous Integration

* *kitchen+travis:* adjust matrix to add `3000.1` & remove `2017.7`
(https://github.com/saltstack-formulas/dhcpd-formula/commit/6bacfb326610ab3afc399e7aaf3c109ef66dfd75[6bacfb3^])

=== Tests

* fix `arch` conditional and make `case` more Rubyish
(https://github.com/saltstack-formulas/dhcpd-formula/commit/0b5bab25c02c63506b9b3701aeff72b587c354ac[0b5bab2^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.10.4...v0.11.0++[0.11.0^] (2020-04-09)

=== Features

* *ldap:* add ldap backend support
(https://github.com/saltstack-formulas/dhcpd-formula/commit/241f2677631311991527381c87a10fb1926cf3c1[241f267^])

=== Tests

* fix tests for PR 44
(https://github.com/saltstack-formulas/dhcpd-formula/commit/5128b1ff45dc88e51ad7221cd0dbc03a817159fa[5128b1f^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.10.3...v0.10.4++[0.10.4^] (2020-04-06)

=== Bug Fixes

* *map.jinja:* ensure whole pillar is merged in
(https://github.com/saltstack-formulas/dhcpd-formula/commit/4baed92e8768e6e7cbd6537c9359d5a28e838387[4baed92^])

=== Code Refactoring

* *tpls:* refactor templates
(https://github.com/saltstack-formulas/dhcpd-formula/commit/9648e0d0872db66e26ca11d6a0d860d6afff79ab[9648e0d^])

=== Tests

* *config_spec:* update according to refactored `map.jinja`
(https://github.com/saltstack-formulas/dhcpd-formula/commit/880b2815ee8102904b6586ded0d1e81412458575[880b281^])
* *yaml_dump_spec:* update according to refactored `map.jinja`
(https://github.com/saltstack-formulas/dhcpd-formula/commit/174e8d22299d3dc464e2b5e0bf11fd280b51c27e[174e8d2^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.10.2...v0.10.3++[0.10.3^] (2020-04-06)

=== Tests

* *config_spec:* fix existing tests (repeating same control twice)
(https://github.com/saltstack-formulas/dhcpd-formula/commit/3c7cd4483a1b012c33e0b0b53f16d3982f8d7e22[3c7cd44^])
* *config_spec:* update with file contents to test
(https://github.com/saltstack-formulas/dhcpd-formula/commit/0ae0a660e8a02481495178e5996b9a0503613a7e[0ae0a66^])
* *config_spec:* workaround spurious whitespace issues on CentOS
(https://github.com/saltstack-formulas/dhcpd-formula/commit/f4e12c58b74d428421e80b77b2a1e92eb128b166[f4e12c5^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.10.1...v0.10.2++[0.10.2^] (2020-04-06)

=== Code Refactoring

* *map:* use `map.jinja` ng
(https://github.com/saltstack-formulas/dhcpd-formula/commit/0ebe7422d82f96484529581dc86dc2867c7348dc[0ebe742^])

=== Tests

* *yaml_dump_spec:* update
(https://github.com/saltstack-formulas/dhcpd-formula/commit/a57912d18a6aa1b94a1455e8d692861f0cc0eb58[a57912d^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.10.0...v0.10.1++[0.10.1^] (2020-04-06)

=== Tests

* *yaml_dump:* add functionality, initial tests & add to Kitchen
(https://github.com/saltstack-formulas/dhcpd-formula/commit/76d43f57595d595883b766c4bded8401d3fd0175[76d43f5^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.9.0...v0.10.0++[0.10.0^] (2020-02-27)

=== Continuous Integration

* *kitchen:* avoid using bootstrap for `master` instances [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/fc755da7657b4161d31389c9db72a383f6751dcc[fc755da^])
* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/9780bc33e621ac3595681bfc31ba65990a5c7afe[9780bc3^])

=== Features

* *map.jinja:* add Red Hat styled service configuration
(https://github.com/saltstack-formulas/dhcpd-formula/commit/ebf6e5060fb82628c58ba99c010c90d746584338[ebf6e50^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.8.1...v0.9.0++[0.9.0^] (2019-12-16)

=== Bug Fixes

* *release.config.js:* use full commit hash in commit link [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/1c516f57e848f0bcb9fe03cb82284a4c3c6bb41c[1c516f5^])

=== Continuous Integration

* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/f838b4d4733452d36d62cfe4ef9b7ee57752a01f[f838b4d^])
* *kitchen:* use `debian-10-master-py3` instead of `develop` [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/7ca8c7a1913fbbf01712a2ce4d5c3d1443f3b6b8[7ca8c7a^])
* *kitchen:* use `develop` image until `master` is ready (`amazonlinux`)
 [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/e009040d28afe4e1bd07156580a18723b9cbb1d5[e009040^])
* *kitchen+travis:* upgrade matrix after `2019.2.2` release [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/d7591f0dcb5d677294685bb7f1acb26245abba5d[d7591f0^])
* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/df6ce3e5d343d07a9ccd33501059edd6359e6343[df6ce3e^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/7fb1a936230e2732d23a9edae11fc4f96fd0daac[7fb1a93^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/67c340d3099c78ee7c0079cde9fb5609fbb54bc6[67c340d^])
* *travis:* run `shellcheck` during lint job [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/4a192fe586bf55e4bb680c51e60828260c2d889d[4a192fe^])
* *travis:* update `salt-lint` config for `v0.0.10` [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/14eecc2114e42f8c97dc66f49250b3bbbae655d5[14eecc2^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/8068a890085582ab499dd7972f6e560a18c39330[8068a89^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/dhcpd-formula/commit/8ed2593917824945b0be96c8120fa564981ef0b5[8ed2593^])

=== Documentation

* *contributing:* remove to use org-level file instead [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/77da7bed48d9b352b9b47f73a2d267220839fb69[77da7be^])
* *readme:* update link to `CONTRIBUTING` [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/d40fd748d8a4b69a1ee03bf5b5b74938e26d6dfc[d40fd74^])

=== Features

* *map.jinja:* add Gentoo support
(https://github.com/saltstack-formulas/dhcpd-formula/commit/934bcf4459529a3c2112402746208555c2f1858e[934bcf4^])

=== Performance Improvements

* *travis:* improve `salt-lint` invocation [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/42a525ddb48107365467bdf952d190bcc67825be[42a525d^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.8.0...v0.8.1++[0.8.1^] (2019-10-09)

=== Continuous Integration

* *kitchen:* change `log_level` to `debug` instead of `info`
(https://github.com/saltstack-formulas/dhcpd-formula/commit/3e11354[3e11354^])
* *kitchen:* install required packages to bootstrapped `opensuse` [skip
ci] (https://github.com/saltstack-formulas/dhcpd-formula/commit/5ec2e57)
* *kitchen:* use bootstrapped `opensuse` images until `2019.2.2` [skip
ci] (https://github.com/saltstack-formulas/dhcpd-formula/commit/f914fe3)
* *kitchen+travis:* replace EOL pre-salted images
(https://github.com/saltstack-formulas/dhcpd-formula/commit/c33b06b[c33b06b^])
* *platform:* add `arch-base-latest` (commented out for now) [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/99c7477[99c7477^])
* *yamllint:* add rule `empty-values` & use new `yaml-files` setting
(https://github.com/saltstack-formulas/dhcpd-formula/commit/0688273[0688273^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/dhcpd-formula/commit/d7c9254[d7c9254^])
* use `dist: bionic` & apply `opensuse-leap-15` SCP error workaround
(https://github.com/saltstack-formulas/dhcpd-formula/commit/5dc28e1[5dc28e1^])

=== Tests

* *inspec:* add remaining platforms [skip ci]
(https://github.com/saltstack-formulas/dhcpd-formula/commit/483d70d[483d70d^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.7.1...v0.8.0++[0.8.0^] (2019-08-10)

=== Features

* *yamllint:* include for this repo and apply rules throughout
(https://github.com/saltstack-formulas/dhcpd-formula/commit/d70c724[d70c724^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.7.0...v0.7.1++[0.7.1^] (2019-07-31)

=== Code Refactoring

* *indent:* use filter block to indent included files
(https://github.com/saltstack-formulas/dhcpd-formula/commit/451667f[451667f^])

== link:++https://github.com/saltstack-formulas/dhcpd-formula/compare/v0.6.0...v0.7.0++[0.7.0^] (2019-07-31)

=== Continuous Integration

* *travis:* initialize kitchen infrastructure
(https://github.com/saltstack-formulas/dhcpd-formula/commit/472a1c4[472a1c4^])

=== Documentation

* *readme:* move under doc/ and add contributing documentation
(https://github.com/saltstack-formulas/dhcpd-formula/commit/523e19a[523e19a^])

=== Features

* *semantic-release:* implement an automated changelog
(https://github.com/saltstack-formulas/dhcpd-formula/commit/b5ad74e[b5ad74e^])

=== Tests

* *config:* the daemon configuration file must exist
(https://github.com/saltstack-formulas/dhcpd-formula/commit/840c225[840c225^])
* *packages:* we have only one installed package
(https://github.com/saltstack-formulas/dhcpd-formula/commit/9b9fa1e[9b9fa1e^])
* *service:* the service configuration file must exist
(https://github.com/saltstack-formulas/dhcpd-formula/commit/eb3c948[eb3c948^])
* *service:* the service must be installed but disabled
(https://github.com/saltstack-formulas/dhcpd-formula/commit/174c2e7[174c2e7^])
